apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloodhound
  labels:
    app: bloodhound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bloodhound
  template:
    metadata:
      labels:
        app: bloodhound
    spec:
      containers:
        - name: afthem
          image: apifortress/bloodhound:latest
          env:
            - name: memorySettings
              value: "-Xms1024m -Xmx2048m"
          resources:
            limits:
              memory: 4Gi
              cpu: 3
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: afthem
              mountPath: /opt/bloodhound/etc
            - name: afthem-flows
              mountPath: /opt/bloodhound/etc/flows
      volumes:
        - name: bloodhound
          configMap:
            name: bloodhound
        - name: bloodhound-flows
          configMap:
            name: bloodhound-flows
---

apiVersion: v1
kind: Service
metadata:
  name: bloodhound
spec:
  type: LoadBalancer
  selector:
    app: bloodhound
  ports:
    - port: 8080
  loadBalancerIP: '[balancer_ip]'
  sessionAffinity: ClientIP
---
